# Generated by Django 3.2.15 on 2022-10-15 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='task_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
